export const FETCH_ALL_GISTS_REQUEST = "FETCH_ALL_GISTS_REQUEST";
export const FETCH_ALL_GISTS_SUCCESS = "FETCH_ALL_GISTS_SUCCESS";
export const FETCH_ALL_GISTS_FAILED = "FETCH_ALL_GISTS_FAILED";


export const FETCH_GIST_REQUEST = "FETCH_GIST_REQUEST";
export const FETCH_GIST_SUCCESS = "FETCH_GIST_SUCCESS";
export const FETCH_GIST_FAILED = "FETCH_GIST_FAILED";